### ISSUE TITLE
Failed building wheel

### ISSUE THREAD

**Issue by anthonyhuang07** [nekitdev/gd.rpc#1]
```zsh
  Building wheel for gd.py (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for gd.py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-install-2nile6v_/gd-py_7d815601cea74f949ed06eed17202960/build.py", line 86, in <module>
          @entrypoint(__name__)
           ^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/entrypoint/core.py", line 41, in __call__
          return self.call(main)
                 ^^^^^^^^^^^^^^^
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/entrypoint/core.py", line 36, in call
          main()
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-install-2nile6v_/gd-py_7d815601cea74f949ed06eed17202960/build.py", line 88, in main
          build({})  # type: ignore
          ^^^^^^^^^
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-install-2nile6v_/gd-py_7d815601cea74f949ed06eed17202960/build.py", line 57, in build
          result = call(build_command(output_path))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 389, in call
          with Popen(*popenargs, **kwargs) as p:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1917, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'poetry'
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/opt/homebrew/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
          return WheelBuilder.make_in(
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
          wb.build(target_dir=directory)
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 123, in build
          self._build(zip_file)
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 172, in _build
          self._run_build_script(self._package.build_script)
        File "/private/var/folders/9b/3qh71ljs1yb6j4qnbycsm3mh0000gn/T/pip-build-env-kr1qgtl2/overlay/lib/python3.11/site-packages/poetry/core/masonry/builders/wheel.py", line 232, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/opt/homebrew/Cellar/python@3.11/3.11.3/bin/python3.11', 'build.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gd.py
Successfully built gd-rpc
Failed to build gd.py
ERROR: Could not build wheels for gd.py, which is required to install pyproject.toml-based projects
```

**Comment by nekitdev** [comment]
`gd.py` was updated to remove `poetry` usage, so everything should work now.
